// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/plan/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plan/delete.post').default>>>>
    }
    '/api/plan/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plan/generate.post').default>>>>
    }
    '/api/plan/ics-url': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plan/ics-url.get').default>>>>
    }
    '/api/plan/ics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plan/ics.get').default>>>>
    }
    '/api/plan/latest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plan/latest.get').default>>>>
    }
    '/api/profile/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/update.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}