// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25/08/2025, 14:40:47
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/plugins/**/*.{js,ts,mjs}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/composables/**/*.{js,ts,mjs}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/utils/**/*.{js,ts,mjs}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/disk2/Test/runplanner-pro-ui-v3-profile-update-fallback/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;